#!/usr/bin/env bash
# Define the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

sudo sed -i "/^[[:space]]*server {/a\\\n\\tlocation /redirect_me {\n\t\treturn 301 https://www.instagram.com/john.sky05;\n\t}" "$nginx_conf"

sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload
