#!/usr/bin/env bash
# Displays "To infinity and beyond" identify with
#+ a sleep 2 in between each iteration
#   Dispays "I am invincible!!!" in between each iteration.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
